#Wesley Murray
#Define a simple data summary project architecture.

services:
  #Set up web app using ASP.NET
  DataReviewApp:
    image: mcr.microsoft.com/dotnet/sdk:5.0
    working_dir: /app
    ports:
      - 5000:5000
    volumes:
      - ../../DataReviewProject:/app
    command: ["dotnet","watch","run"]
    networks:
      DataReviewNetwork:
        ipv4_address: 172.20.0.3

  #Set up MongoDB Database
  DataReviewDatabase:
    image: mongo:latest
    restart: always
    env_file: 
      - ./mongodb-secrets.env
      - ./mongodb-config.env
    networks:
      DataReviewNetwork:
        ipv4_address: 172.20.0.2

#Add Network
networks:
  DataReviewNetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1